"""add_indexes_and_cascade_deletes

Revision ID: 3b89b07f7778
Revises: 2c33bc764aa5
Create Date: 2025-05-31 11:58:35.742764

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b89b07f7778'
down_revision: Union[str, None] = '2c33bc764aa5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Add index to user_id in projects table.
    
    Note: Foreign key ON DELETE behavior is defined in the SQLAlchemy model definitions,
    which will be used when tables are created. Since SQLite doesn't support altering
    foreign key constraints directly, we'll only add the index here, and the CASCADE/SET NULL
    behaviors will be applied to new database instances or when tables are recreated.
    """
    # Create index on user_id in projects table
    op.create_index(op.f('ix_projects_user_id'), 'projects', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Remove the user_id index from projects table."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_projects_user_id'), table_name='projects')
    # ### end Alembic commands ###
