"""Add coordination workflow ID to projects

Revision ID: 8299a7f134a4
Revises: 6a723c60c15d
Create Date: 2025-06-01 15:28:15.696157

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8299a7f134a4'
down_revision: Union[str, None] = '6a723c60c15d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('coordination_workflow_id', sa.String(length=255), nullable=True))
    # Note: SQLite doesn't support altering column types, so we skip the enum change
    # The application will handle the new enum values in the string column
    op.create_index(op.f('ix_projects_coordination_workflow_id'), 'projects', ['coordination_workflow_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_projects_coordination_workflow_id'), table_name='projects')
    op.drop_column('projects', 'coordination_workflow_id')
    # ### end Alembic commands ###
